import { Response } from "express";
import { AuthenticatedRequest } from "../middleware/authMiddleware";
import { query } from "../config/database";

export const getAuditLogs = async (
    req: AuthenticatedRequest,
    res: Response
): Promise<void> => {
    try {
        const userRole = req.user?.role;

        if (
            userRole !== "SUPER_ADMIN" &&
            userRole !== "DEPARTMENT_ADMIN"
        ) {
            res.status(403).json({
                success: false,
                message: "You are not authorized to view audit logs",
            });
            return;
        }

        const {
            action,
            entityType,
            userId,
            fromDate,
            toDate,
        } = req.query;

        const conditions: string[] = [];
        const params: unknown[] = [];

        const addParam = (value: unknown) => {
            params.push(value);
            return `$${params.length}`;
        };

        /*
         * Department Admin:
         * Only see audit logs generated by users
         * belonging to their own site/department.
         */
        if (userRole === "DEPARTMENT_ADMIN") {
            if (
                req.user?.siteId === null ||
                req.user?.siteId === undefined ||
                req.user?.departmentId === null ||
                req.user?.departmentId === undefined
            ) {
                res.status(403).json({
                    success: false,
                    message:
                        "Department Admin is not properly configured",
                });
                return;
            }

            const siteParam = addParam(req.user.siteId);
            const departmentParam = addParam(
                req.user.departmentId
            );

            conditions.push(`
                (
                    u.site_id = ${siteParam}
                    AND u.department_id = ${departmentParam}
                )
            `);
        }

        if (action) {
            conditions.push(
                `a.action = ${addParam(String(action))}`
            );
        }

        if (entityType) {
            conditions.push(
                `a.entity_type = ${addParam(
                    String(entityType)
                )}`
            );
        }

        if (userId) {
            conditions.push(
                `a.user_id = ${addParam(Number(userId))}`
            );
        }

        if (fromDate) {
            conditions.push(
                `a.created_at >= ${addParam(
                    String(fromDate)
                )}::date`
            );
        }

        if (toDate) {
            conditions.push(
                `a.created_at < (
                    ${addParam(String(toDate))}::date
                    + INTERVAL '1 day'
                )`
            );
        }

        const whereClause =
            conditions.length > 0
                ? `WHERE ${conditions.join(" AND ")}`
                : "";

        const result = await query(
            `
            SELECT
                a.id,
                a.user_id,
                a.action,
                a.entity_type,
                a.entity_id,
                a.old_data,
                a.new_data,
                a.ip_address,
                a.created_at,

                u.user_id AS user_code,
                u.full_name AS user_name,

                i.incident_no

            FROM audit_logs a

            LEFT JOIN users u
                ON u.id = a.user_id

            LEFT JOIN incidents i
                ON a.entity_type = 'INCIDENT'
                AND i.id = a.entity_id

            ${whereClause}

            ORDER BY a.created_at DESC

            LIMIT 500
            `,
            params
        );

        res.json({
            success: true,
            data: result.rows,
        });
    } catch (error) {
        console.error(
            "Get audit logs error:",
            error
        );

        res.status(500).json({
            success: false,
            message: "Failed to fetch audit logs",
        });
    }
};
